# Generated by Django 4.0 on 2022-01-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Field', models.CharField(max_length=50)),
                ('Employeeid', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
